In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('train (24).csv')

In [3]:
df.head()

Timestamp  Temperature  Dew Point  Surface Albedo  Pressure  \
0  2019-01-01 00:00:00         12.5        6.9            0.21      1005   
1  2019-01-01 00:10:00         12.3        6.9            0.21      1005   
2  2019-01-01 00:20:00         12.1        6.9            0.21      1005   
3  2019-01-01 00:30:00         12.0        6.9            0.21      1005   
4  2019-01-01 00:40:00         11.8        6.9            0.21      1005   

   Wind Direction  Wind Speed  Clearsky DHI  Clearsky DNI  Clearsky GHI  \
0             121         1.0             0             0             0   
1             122         1.0             0             0             0   
2             124         1.0             0             0             0   
3             125         1.0             0             0             0   
4             126         1.0             0             0             0   

   Fill Flag  Ozone  Cloud Type  Solar Zenith Angle  Precipitable Water  \
0          0  0.258           1              173.92                 1.4   
1          0  0.258           1              171.79                 1.3   
2          0  0.258           1              169.59                 1.3   
3          0  0.258           1              167.37                 1.3   
4          0  0.258           1              165.13                 1.3   

   Relative Humidity  
0              68.82  
1              69.73  
2              70.65  
3              71.11  
4              71.91

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210240 entries, 0 to 210239
Data columns (total 16 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   Timestamp           210240 non-null  object 
 1   Temperature         210240 non-null  float64
 2   Dew Point           210240 non-null  float64
 3   Surface Albedo      210240 non-null  float64
 4   Pressure            210240 non-null  int64  
 5   Wind Direction      210240 non-null  int64  
 6   Wind Speed          210240 non-null  float64
 7   Clearsky DHI        210240 non-null  int64  
 8   Clearsky DNI        210240 non-null  int64  
 9   Clearsky GHI        210240 non-null  int64  
 10  Fill Flag           210240 non-null  int64  
 11  Ozone               210240 non-null  float64
 12  Cloud Type          210240 non-null  int64  
 13  Solar Zenith Angle  210240 non-null  float64
 14  Precipitable Water  210240 non-null  float64
 15  Relative Humidity   210240 non-nul

In [5]:
data = df.drop("Timestamp", axis=1)

In [6]:
data.head()

Temperature  Dew Point  Surface Albedo  Pressure  Wind Direction  \
0         12.5        6.9            0.21      1005             121   
1         12.3        6.9            0.21      1005             122   
2         12.1        6.9            0.21      1005             124   
3         12.0        6.9            0.21      1005             125   
4         11.8        6.9            0.21      1005             126   

   Wind Speed  Clearsky DHI  Clearsky DNI  Clearsky GHI  Fill Flag  Ozone  \
0         1.0             0             0             0          0  0.258   
1         1.0             0             0             0          0  0.258   
2         1.0             0             0             0          0  0.258   
3         1.0             0             0             0          0  0.258   
4         1.0             0             0             0          0  0.258   

   Cloud Type  Solar Zenith Angle  Precipitable Water  Relative Humidity  
0           1              173.92                 1.4              68.82  
1           1              171.79                 1.3              69.73  
2           1              169.59                 1.3              70.65  
3           1              167.37                 1.3              71.11  
4           1              165.13                 1.3              71.91

In [7]:
data.isnull().sum()

Temperature           0
Dew Point             0
Surface Albedo        0
Pressure              0
Wind Direction        0
Wind Speed            0
Clearsky DHI          0
Clearsky DNI          0
Clearsky GHI          0
Fill Flag             0
Ozone                 0
Cloud Type            0
Solar Zenith Angle    0
Precipitable Water    0
Relative Humidity     0
dtype: int64

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210240 entries, 0 to 210239
Data columns (total 15 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   Temperature         210240 non-null  float64
 1   Dew Point           210240 non-null  float64
 2   Surface Albedo      210240 non-null  float64
 3   Pressure            210240 non-null  int64  
 4   Wind Direction      210240 non-null  int64  
 5   Wind Speed          210240 non-null  float64
 6   Clearsky DHI        210240 non-null  int64  
 7   Clearsky DNI        210240 non-null  int64  
 8   Clearsky GHI        210240 non-null  int64  
 9   Fill Flag           210240 non-null  int64  
 10  Ozone               210240 non-null  float64
 11  Cloud Type          210240 non-null  int64  
 12  Solar Zenith Angle  210240 non-null  float64
 13  Precipitable Water  210240 non-null  float64
 14  Relative Humidity   210240 non-null  float64
dtypes: float64(8), int64(7)
memory usa

In [9]:
#Clearsky DHI

X = data.drop(['Clearsky DHI', 'Clearsky DNI', 'Clearsky GHI'], axis = 1)
y_DHI = data['Clearsky DHI']

In [10]:
#Clearsky DNI

y_DNI = data['Clearsky DNI']

In [11]:
#Clearsky GHI

y_GHI = data['Clearsky GHI']

In [12]:
#standardization

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(X)

In [13]:
X

array([[-1.65473565, -0.63975669, -0.0777113 , ...,  1.96427707,
        -0.87428043,  0.5205199 ],
       [-1.6778861 , -0.63975669, -0.0777113 , ...,  1.91457172,
        -0.91848999,  0.55116734],
       [-1.70103655, -0.63975669, -0.0777113 , ...,  1.86323286,
        -0.91848999,  0.58215155],
       ...,
       [-2.31452344, -0.74723276, -0.0777113 , ...,  2.04338558,
        -0.69744219,  1.34362234],
       [-2.31452344, -0.76677387, -0.0777113 , ...,  2.04455237,
        -0.69744219,  1.29950351],
       [-2.31452344, -0.76677387, -0.0777113 , ...,  2.00978197,
        -0.69744219,  1.29950351]])

In [14]:
#train test split

from sklearn.model_selection import train_test_split

In [15]:
#dhi

X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y_DHI, test_size = 0.3, random_state=43)

In [16]:
#dni

X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y_DNI, test_size = 0.3, random_state=43)

In [17]:
#ghi

X_train3, X_test3, y_train3, y_test3 = train_test_split(X, y_GHI, test_size = 0.3, random_state=43)

In [18]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import *

In [19]:
model = RandomForestRegressor()

In [20]:
model_dhi = model.fit(X_train1,y_train1)

In [21]:
pred_dhi = model_dhi.predict(X_test1) #y_test1

In [22]:
pred_dhi

array([  0.  ,   0.  ,   0.  , ..., 334.67, 197.67, 278.55])

In [23]:
mean_squared_error(y_test1, pred_dhi)

129.08979470287926

In [24]:
r2_score(y_test1, pred_dhi)

0.9911035106102839

In [28]:
#dni
model2 = RandomForestRegressor()

model_dni = model2.fit(X_train2,y_train2)

pred_dni = model_dni.predict(X_test2) #y_test2

mean_squared_error(pred_dni, y_test2)

1082.710202814244

In [29]:
r2_score(pred_dni, y_test2)

0.9855946057256004

In [30]:
#ghi
model3 = RandomForestRegressor()

model_ghi = model3.fit(X_train3,y_train3)

pred_ghi = model_ghi.predict(X_test3) #y_test3

mean_squared_error(pred_ghi, y_test3)

120.53597061136477

In [31]:
r2_score(pred_ghi, y_test3)

0.9988585565933202

In [21]:
test = pd.read_csv("test (2).csv")

In [22]:
test.head()

Timestamp  Temperature  Dew Point  Surface Albedo  Pressure  \
0  2023-01-01 00:00:00         11.3        1.6            0.21      1006   
1  2023-01-01 00:10:00         11.2        1.6            0.21      1006   
2  2023-01-01 00:20:00         11.1        1.6            0.21      1006   
3  2023-01-01 00:30:00         11.0        1.6            0.21      1006   
4  2023-01-01 00:40:00         10.9        1.2            0.21      1006   

   Wind Direction  Wind Speed  Clearsky DHI  Clearsky DNI  Clearsky GHI  \
0             305         1.2           NaN           NaN           NaN   
1             306         1.2           NaN           NaN           NaN   
2             306         1.2           NaN           NaN           NaN   
3             307         1.2           NaN           NaN           NaN   
4             307         1.2           NaN           NaN           NaN   

   Fill Flag  Ozone  Cloud Type  Solar Zenith Angle  Precipitable Water  \
0          0  0.255           0              173.92                 1.4   
1          0  0.255           0              171.79                 1.4   
2          0  0.255           0              169.59                 1.4   
3          0  0.255           0              167.37                 1.4   
4          0  0.255           0              165.13                 1.4   

   Relative Humidity  
0              51.38  
1              51.72  
2              52.06  
3              52.41  
4              51.34

In [23]:
test = test.drop(['Timestamp','Clearsky DHI', 'Clearsky DNI', 'Clearsky GHI'], axis=1)

In [24]:
test = sc.fit_transform(test)

In [25]:
#dhi pred

pred1 = model.predict(test)

In [26]:
pred1

array([0., 0., 0., ..., 0., 0., 0.])

In [32]:
#dni

pred2 = model2.predict(test)

In [34]:
pred2

array([0., 0., 0., ..., 0., 0., 0.])

In [33]:
#ghi

pred3 = model3.predict(test)

In [35]:
pred3

array([0., 0., 0., ..., 0., 0., 0.])

In [37]:
pred1 = pd.DataFrame(pred1)
pred1

0
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
...    ...
52555  0.0
52556  0.0
52557  0.0
52558  0.0
52559  0.0

[52560 rows x 1 columns]

In [38]:
pred1.to_csv("pred1.csv")

In [39]:
#pycaret

In [2]:
!pip install pycaret

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 5.1.5 requires pyqt5<5.13, which is not installed.
spyder 5.1.5 requires pyqtwebengine<5.13, which is not installed.



  Using cached pycaret-3.0.4-py3-none-any.whl (484 kB)
  Using cached category_encoders-2.6.1-py2.py3-none-any.whl (81 kB)
  Using cached imbalanced_learn-0.11.0-py3-none-any.whl (235 kB)
  Using cached scikit_plot-0.3.7-py3-none-any.whl (33 kB)
  Using cached sktime-0.21.0-py3-none-any.whl (17.1 MB)
  Using cached psutil-5.9.5-cp36-abi3-win_amd64.whl (255 kB)
  Using cached deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
  Using cached yellowbrick-1.5-py3-none-any.whl (282 kB)
  Using cached schemdraw-0.15-py3-none-any.whl (106 kB)
  Using cached pyod-1.1.0-py3-none-any.whl
  Using cached lightgbm-4.0.0-py3-none-win_amd64.whl (1.3 MB)
  Using cached xxhash-3.3.0-cp39-cp39-win_amd64.whl (29 kB)
  Using cached tbats-1.1.3-py3-none-any.whl (44 kB)
  Using cached plotly_resampler-0.9.1-py3-none-any.whl (73 kB)
  Using cached importlib_metadata-6.8.0-py3-none-any.whl (22 kB)
  Using cached kaleido-0.2.1-py2.py3-none-win_amd64.whl (65.9 MB)
  Using cached joblib-1.3.1-py3-none-any.whl (301 

In [3]:
from pycaret.regression import *


  Attempting uninstall: joblib
    Found existing installation: joblib 1.1.0
    Uninstalling joblib-1.1.0:
      Successfully uninstalled joblib-1.1.0
  Attempting uninstall: psutil
    Found existing installation: psutil 5.8.0
    Uninstalling psutil-5.8.0:
      Successfully uninstalled psutil-5.8.0
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib-metadata 4.11.3
    Uninstalling importlib-metadata-4.11.3:
      Successfully uninstalled importlib-metadata-4.11.3


In [5]:
import pandas as pd
data = pd.read_csv("train (24).csv")

In [6]:
new = data.drop(['Timestamp', 'Clearsky DHI', 'Clearsky GHI'], axis=1)

In [7]:
s = setup(new, target='Clearsky DNI',session_id = 222)

In [8]:
best = compare_models()

Initiated  . . . . . . . . . . . . . . . . . .               22:22:49
Status     . . . . . . . . . . . . . . . . . .       Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Extra Trees Regressor

Processing:   0%|          | 0/81 [00:00<?, ?it/s]

KeyboardInterrupt: 